---
## TODO
## Configure a vm on libvirt IF the previous role install_libvirt succeeds. ---> TBD


- name: Define domain(s) (guest VM)
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'domains/{{ item }}.xml.j2') }}"
    uri: qemu:///system
  with_items: "{{ libvirt_guest_names }}"

- name: Start domain
  community.libvirt.virt:
    name: "{{ item }}"
    state: running
    autostart: no
    uri: 'qemu:///system'
  with_items: "{{ libvirt_guest_names }}"


# - name: List all domains (VM)
#   community.libvirt.virt:
#     command: list_vms
#   register: all_vms

# - name: Show all domains (VM)
#   debug:
#     var: all_vms.stdout

...