services:
  ldap:
    image: ldap
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ldap
    hostname: ldap
    ports:
      - 389
    network_mode: host
# networks:
#   default:
#     name: devanet
#     external: true
